import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Card,
  CardContent,
  Grid,
  Button,
  Alert,
  CircularProgress,
  Chip,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  Divider,
  Paper
} from '@mui/material';
import {
  Groups as GroupsIcon,
  Assignment as AssignmentIcon,
  TrendingUp as TrendingUpIcon,
  CheckCircle as CheckCircleIcon,
  Schedule as ScheduleIcon,
  Message as MessageIcon,
  FileDownload as FileDownloadIcon,
  Refresh as RefreshIcon,
  Warning as WarningIcon
} from '@mui/icons-material';
import Layout from './Layout';
import IncidentHeatmap from './IncidentHeatmap';
import api from '../utils/api';

const ManagerDashboard = ({ user, onLogout }) => {
  const [stats, setStats] = useState(null);
  const [recentIncidents, setRecentIncidents] = useState([]);
  const [teams, setTeams] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [messageDialog, setMessageDialog] = useState(false);
  const [reportGenerating, setReportGenerating] = useState(false);

  const fetchDashboardData = async () => {
    try {
      setLoading(true);
      
      // Fetch multiple data sources in parallel
      const [statsResponse, incidentsResponse, teamsResponse] = await Promise.all([
        api.get('/manager/stats').catch(() => ({ data: null })), // Allow stats to fail
        api.get('/manager/incidents').catch(() => ({ data: [] })),
        api.get('/manager/teams').catch(() => ({ data: [] }))
      ]);

      setStats(statsResponse.data);
      setRecentIncidents(incidentsResponse.data.slice(0, 5)); // Get last 5 incidents
      setTeams(teamsResponse.data);
    } catch (err) {
      console.error('Error fetching dashboard data:', err);
      setError('Failed to fetch dashboard data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDashboardData();
  }, []);

  const handleSendMessage = async (recipientType) => {
    try {
      // For now, just show success message
      // TODO: Implement actual messaging functionality
      await api.post('/manager/message', {
        message: `Hello ${recipientType === 'admins' ? 'Admins' : 'Team Leaders'}, this is a message from ${user.name}`,
        to: recipientType
      });
      
      alert('Message sent successfully!');
      setMessageDialog(false);
    } catch (err) {
      console.error('Error sending message:', err);
      alert('Failed to send message');
    }
  };

  const handleDownloadReport = async () => {
    try {
      setReportGenerating(true);
      
      // Generate report data
      const reportData = {
        generatedBy: user.name,
        generatedAt: new Date().toISOString(),
        summary: stats?.summary || {},
        teams: teams,
        recentIncidents: recentIncidents
      };

      // Create and download CSV
      const csvContent = [
        'Field,Value',
        `Report Generated,${reportData.generatedAt}`,
        `Generated By,${reportData.generatedBy}`,
        `Total Incidents,${reportData.summary.totalIncidents || 0}`,
        `Total Teams,${reportData.summary.totalTeams || 0}`,
        `Total Members,${reportData.summary.totalMembers || 0}`,
        `Average Completion Rate,${reportData.summary.averageCompletionRate || 0}%`,
        '',
        'Team Performance',
        'Team Name,Members,Total Jobs,Completed Jobs,Completion Rate',
        ...teams.map(team => {
          const completionRate = team.JobCards?.length > 0
            ? Math.round((team.JobCards.filter(job => job.status === 'completed').length / team.JobCards.length) * 100)
            : 0;
          return `${team.name},${team.TeamMembers?.length || 0},${team.JobCards?.length || 0},${team.JobCards?.filter(job => job.status === 'completed').length || 0},${completionRate}%`;
        })
      ].join('\n');

      const blob = new Blob([csvContent], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.style.display = 'none';
      a.href = url;
      a.download = `manager-report-${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

    } catch (err) {
      console.error('Error generating report:', err);
      alert('Failed to generate report');
    } finally {
      setReportGenerating(false);
    }
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'pending':
        return 'warning';
      case 'verified':
        return 'info';
      case 'assigned':
        return 'primary';
      case 'in_progress':
        return 'secondary';
      case 'completed':
        return 'success';
      default:
        return 'default';
    }
  };

  if (loading) {
    return (
      <Layout user={user} onLogout={onLogout}>
        <Box display="flex" justifyContent="center" alignItems="center" minHeight="200px">
          <CircularProgress />
        </Box>
      </Layout>
    );
  }

  return (
    <Layout user={user} onLogout={onLogout}>
      <Box sx={{ p: 3 }}>
        <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
          <Box>
            <Typography variant="h4" component="h1" gutterBottom>
              Manager Dashboard
            </Typography>
            <Typography variant="body1" color="text.secondary">
              Welcome back, {user.name}
            </Typography>
          </Box>
          <Box display="flex" gap={1}>
            <Button
              variant="outlined"
              startIcon={<RefreshIcon />}
              onClick={fetchDashboardData}
            >
              Refresh
            </Button>
            <Button
              variant="contained"
              startIcon={<FileDownloadIcon />}
              onClick={handleDownloadReport}
              disabled={reportGenerating}
            >
              {reportGenerating ? 'Generating...' : 'Download Report'}
            </Button>
          </Box>
        </Box>

        {error && (
          <Alert severity="warning" sx={{ mb: 2 }} onClose={() => setError('')}>
            {error}
          </Alert>
        )}

        {/* Quick Actions */}
        <Paper sx={{ p: 2, mb: 3 }}>
          <Typography variant="h6" gutterBottom>
            Quick Actions
          </Typography>
          <Grid container spacing={2}>
            <Grid item xs={12} sm={6} md={3}>
              <Button
                fullWidth
                variant="outlined"
                startIcon={<GroupsIcon />}
                href="#/teams"
              >
                Manage Teams
              </Button>
            </Grid>
            <Grid item xs={12} sm={6} md={3}>
              <Button
                fullWidth
                variant="outlined"
                startIcon={<AssignmentIcon />}
                href="#/incidents"
              >
                View Incidents
              </Button>
            </Grid>
            <Grid item xs={12} sm={6} md={3}>
              <Button
                fullWidth
                variant="outlined"
                startIcon={<TrendingUpIcon />}
                href="#/stats"
              >
                View Statistics
              </Button>
            </Grid>
            <Grid item xs={12} sm={6} md={3}>
              <Button
                fullWidth
                variant="outlined"
                startIcon={<MessageIcon />}
                onClick={() => setMessageDialog(true)}
              >
                Send Message
              </Button>
            </Grid>
          </Grid>
        </Paper>

        {/* Summary Cards */}
        <Grid container spacing={3} sx={{ mb: 4 }}>
          <Grid item xs={12} sm={6} md={3}>
            <Card>
              <CardContent sx={{ textAlign: 'center' }}>
                <AssignmentIcon color="primary" sx={{ fontSize: 40, mb: 1 }} />
                <Typography variant="h4" color="primary">
                  {stats?.summary?.totalIncidents || 0}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Total Incidents
                </Typography>
              </CardContent>
            </Card>
          </Grid>
          
          <Grid item xs={12} sm={6} md={3}>
            <Card>
              <CardContent sx={{ textAlign: 'center' }}>
                <GroupsIcon color="primary" sx={{ fontSize: 40, mb: 1 }} />
                <Typography variant="h4" color="primary">
                  {stats?.summary?.totalTeams || 0}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Total Teams
                </Typography>
              </CardContent>
            </Card>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <Card>
              <CardContent sx={{ textAlign: 'center' }}>
                <CheckCircleIcon color="success" sx={{ fontSize: 40, mb: 1 }} />
                <Typography variant="h4" color="success.main">
                  {stats?.summary?.totalMembers || 0}
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Team Members
                </Typography>
              </CardContent>
            </Card>
          </Grid>

          <Grid item xs={12} sm={6} md={3}>
            <Card>
              <CardContent sx={{ textAlign: 'center' }}>
                <TrendingUpIcon color="secondary" sx={{ fontSize: 40, mb: 1 }} />
                <Typography variant="h4" color="secondary.main">
                  {stats?.summary?.averageCompletionRate || 0}%
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Avg Completion Rate
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        </Grid>

        <Grid container spacing={3}>
          {/* Recent Incidents */}
          <Grid item xs={12} md={6}>
            <Card>
              <CardContent>
                <Typography variant="h6" gutterBottom>
                  Recent Incidents
                </Typography>
                {recentIncidents.length > 0 ? (
                  <List>
                    {recentIncidents.map((incident, index) => (
                      <React.Fragment key={incident.id}>
                        <ListItem>
                          <ListItemIcon>
                            <AssignmentIcon />
                          </ListItemIcon>
                          <ListItemText
                            primary={incident.title}
                            secondary={
                              <Box>
                                <Typography variant="caption" color="text.secondary">
                                  {new Date(incident.created_at).toLocaleDateString()}
                                </Typography>
                                <Box display="flex" gap={1} mt={1}>
                                  <Chip
                                    label={incident.status.replace('_', ' ')}
                                    size="small"
                                    color={getStatusColor(incident.status)}
                                  />
                                </Box>
                              </Box>
                            }
                          />
                        </ListItem>
                        {index < recentIncidents.length - 1 && <Divider />}
                      </React.Fragment>
                    ))}
                  </List>
                ) : (
                  <Typography variant="body2" color="text.secondary" sx={{ textAlign: 'center', py: 2 }}>
                    No recent incidents
                  </Typography>
                )}
                <Button
                  fullWidth
                  variant="outlined"
                  href="#/incidents"
                  sx={{ mt: 2 }}
                >
                  View All Incidents
                </Button>
              </CardContent>
            </Card>
          </Grid>

          {/* Team Overview */}
          <Grid item xs={12} md={6}>
            <Card>
              <CardContent>
                <Typography variant="h6" gutterBottom>
                  Team Overview
                </Typography>
                {teams.length > 0 ? (
                  <List>
                    {teams.map((team, index) => {
                      const totalJobs = team.JobCards?.length || 0;
                      const completedJobs = team.JobCards?.filter(job => job.status === 'completed').length || 0;
                      const pendingJobs = totalJobs - completedJobs;
                      const memberCount = team.TeamMembers?.length || 0;
                      const completionRate = totalJobs > 0 ? Math.round((completedJobs / totalJobs) * 100) : 0;

                      return (
                        <React.Fragment key={team.id}>
                          <ListItem>
                            <ListItemIcon>
                              <GroupsIcon />
                            </ListItemIcon>
                            <ListItemText
                              primary={team.name}
                              secondary={
                                <Box>
                                  <Typography variant="caption" color="text.secondary">
                                    {memberCount} members • {totalJobs} jobs • {completedJobs} completed
                                  </Typography>
                                  <Box display="flex" gap={1} mt={1}>
                                    <Chip
                                      label={`${completionRate}% Complete`}
                                      size="small"
                                      color={completionRate >= 80 ? 'success' : completionRate >= 50 ? 'warning' : 'error'}
                                    />
                                    {pendingJobs > 0 && (
                                      <Chip
                                        label={`${pendingJobs} Pending`}
                                        size="small"
                                        variant="outlined"
                                      />
                                    )}
                                  </Box>
                                </Box>
                              }
                            />
                          </ListItem>
                          {index < teams.length - 1 && <Divider />}
                        </React.Fragment>
                      );
                    })}
                  </List>
                ) : (
                  <Typography variant="body2" color="text.secondary" sx={{ textAlign: 'center', py: 2 }}>
                    No teams created yet
                  </Typography>
                )}
                <Button
                  fullWidth
                  variant="outlined"
                  href="#/teams"
                  sx={{ mt: 2 }}
                >
                  Manage Teams
                </Button>
              </CardContent>
            </Card>
          </Grid>
        </Grid>

        {/* Incident Heatmap */}
        <Grid container spacing={3} sx={{ mt: 2 }}>
          <Grid item xs={12}>
            <IncidentHeatmap />
          </Grid>
        </Grid>

        {/* Status Alerts */}
        {stats?.statusDistribution && (
          <Grid container spacing={3} sx={{ mt: 2 }}>
            <Grid item xs={12}>
              <Paper sx={{ p: 2 }}>
                <Typography variant="h6" gutterBottom>
                  Status Overview
                </Typography>
                <Box display="flex" flexWrap="wrap" gap={1}>
                  {Object.entries(stats.statusDistribution).map(([status, count]) => (
                    <Chip
                      key={status}
                      label={`${status.replace('_', ' ').toUpperCase()}: ${count}`}
                      color={getStatusColor(status)}
                      variant="outlined"
                    />
                  ))}
                </Box>
              </Paper>
            </Grid>
          </Grid>
        )}

        {/* Message Dialog (placeholder) */}
        {messageDialog && (
          <Box
            sx={{
              position: 'fixed',
              top: 0,
              left: 0,
              width: '100%',
              height: '100%',
              backgroundColor: 'rgba(0,0,0,0.5)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              zIndex: 1000
            }}
            onClick={() => setMessageDialog(false)}
          >
            <Paper
              sx={{ p: 3, maxWidth: 400, width: '90%' }}
              onClick={(e) => e.stopPropagation()}
            >
              <Typography variant="h6" gutterBottom>
                Send Message
              </Typography>
              <Typography variant="body2" sx={{ mb: 2 }}>
                Choose who you want to send a message to:
              </Typography>
              <Box display="flex" gap={1} justifyContent="center">
                <Button
                  variant="contained"
                  onClick={() => handleSendMessage('admins')}
                >
                  Send to Admins
                </Button>
                <Button
                  variant="contained"
                  onClick={() => handleSendMessage('team_leaders')}
                >
                  Send to Team Leaders
                </Button>
              </Box>
              <Button
                fullWidth
                sx={{ mt: 2 }}
                onClick={() => setMessageDialog(false)}
              >
                Cancel
              </Button>
            </Paper>
          </Box>
        )}
      </Box>
    </Layout>
  );
};

export default ManagerDashboard;